# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Redis
data:
  redis:
    host: localhost
    port: 6379

# Explicit routes for better control
spring:
  cloud:
    gateway:
      server:
        webflux:
          forwarded:
            enabled: true
          x-forwarded:
            enabled: true
          routes:             # Gateway Manual Routes
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/v1/customers/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: '#{@ipKeyResolver}'
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40
                    redis-rate-limiter.requestedTokens: 5
                - name: CircuitBreaker
                  args:
                    name: customerServiceCB
                    fallbackUri: forward:/fallback/customer-service

            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/identity/**
              filters:
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10     #saniyede kovaya kaç token dolsun?
                    redis-rate-limiter.burstCapacity: 20     #kovanın maks. token kapasitesi.
                    redis-rate-limiter.requestedTokens: 1    #bir isteğin kovadan kaç token düşüreceği?
                - name: CircuitBreaker
                  args:
                    name: identityServiceCB
                    fallbackUri: forward:/fallback/identity-service

# Logging
logging:
  level:
    com.turkcell.gatewayserver: DEBUG
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO

# Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20                         #son kaç isteğe bakayım?
        minimumNumberOfCalls: 10                      #en az 10 çağrı gelmeden % karar mek. çalışmasın.
        failureRateThreshold: 50                      #en az 10 çağrı geldi -> bunların % kaçı başarısızca CB open olsun?
        waitDurationInOpenState: 10s                  #CB open olduktan kaç sn sonra half_open'a geçsin?
        permittedNumberOfCallsInHalfOpenState: 10     #half-open durumdayken kaç test isteği atılsın?
    instances:
      identityServiceCB:
        baseConfig: default
      customerServiceCB:
        baseConfig: default
